name: Testing application

on:
  push:
    branches: "master"


jobs:
   my_test:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         target: [ x86_64-unknown-linux-gnu ]
    
     permissions:
       contents: write
      
     steps:
     - uses: actions/checkout@v3
       with:
         submodules: 'recursive'

         
     - name: Checkout
       uses: actions/checkout@v2
     - name: Setup Bats and bats libs
       run: |
         git clone https://github.com/bats-core/bats-core.git &&
         cd bats-core &&
         sudo ./install.sh /usr/local &&
         cd ..
     - name: Dependencies
       run: |
        sudo apt-get install -y --no-install-recommends \
        libelf1 libelf-dev zlib1g-dev libclang-13-dev \
        make git clang llvm pkg-config build-essential libyaml-dev lsb
     - name: install libcyaml
       run: git clone https://github.com/tlsa/libcyaml.git && cd libcyaml && sudo make install        
     - name: Build
       run: |
         make build
     - name: Run and Test
       run: |
         LD_LIBRARY_PATH=/usr/local/lib && export LD_LIBRARY_PATH && sudo ldconfig && sudo ./src/eBPF_ls src/config.yaml & cd src && sudo bats test.sh
     - name: Testing
       run: |
         cd src && sudo bats test.sh
